const fs = require('fs');
const path = require('path');

let idCounter = 100;

function word(w, pos, pronunciation, def, etym, mEx, cEx, tags, syns, ants) {
  idCounter++;
  return {
    id: idCounter,
    word: w,
    pos: pos,
    pronunciation: pronunciation,
    definition: def,
    etymology: etym,
    manuscriptExample: mEx,
    conferenceExample: cEx,
    tags: tags || ["Life Sciences", "Peer Review"],
    synonyms: syns || [],
    antonyms: ants || []
  };
}

const vocab = {};

vocab.a = [
  word("Aberration", "noun", "/ˌæb.əˈreɪ.ʃən/", "A departure from what is normal, usual, or expected, typically an unwelcome one.", "From Latin aberratio ('wandering away').", "Chromosomal aberrations were quantified in lymphocytes using high-resolution spectral karyotyping.", "The reviewer questioned whether the signal intensity drop was a technical aberration or true apoptosis.", ["Life Sciences", "Peer Review"], ["Anomalous event", "Deviation", "Irregularity"], ["Conformity", "Normality"]),
  word("Abrogate", "verb", "/ˈæb.rə.ɡeɪt/", "To repeal or do away with a formal rule, mechanism, or cellular pathway constraint.", "From Latin abrogatus ('repealed').", "Pharmacological inhibition abrogated the protective effect of antioxidant pre-treatment.", "We inquired whether genetic rescue could abrogate the lethal phenotype observed in homozygous mutants.", ["Peer Review", "Manuscript Editing"], ["Abolish", "Nullify", "Override"], ["Establish", "Enforce", "Validate"]),
  word("Abstruse", "adj.", "/æbˈstruːs/", "Difficult to understand; obscure or esoteric in theoretical formulation.", "From Latin abstrusus ('hidden away').", "The reviewer noted that the theoretical physics derivation was needlessly abstruse for a general biology audience.", "In the editorial board meeting, we recommended simplifying the abstruse mathematical model.", ["Editorial Meetings", "Peer Review"], ["Recondite", "Esoteric", "Arcane"], ["Clear", "Lucid", "Accessible"]),
  word("Acclimatization", "noun", "/əˌklaɪ.mə.taɪˈzeɪ.ʃən/", "The process by which an organism adjusts to a change in its environment over time.", "From French acclimatation.", "Acute physiological acclimatization to hypoxia was tracked across a 14-day altitude exposure trial.", "The referee asked if mouse strain acclimatization times were standardized prior to behavioural testing.", ["Life Sciences"], ["Adaptation", "Habitualization", "Accommodation"], ["Maladaptation"]),
  word("Acquiesce", "verb", "/ˌæk.wiˈes/", "To accept something reluctantly but without protest in manuscript revision.", "From Latin acquiescere ('to find rest in').", "The authors acquiesced to the editor's request for additional Western blot replicates.", "After extensive debate, the panel acquiesced to publishing the short communication.", ["Editorial Meetings", "Peer Review"], ["Comply", "Concede", "Yield"], ["Dissent", "Refuse", "Protest"]),
  word("Acumen", "noun", "/ˈæk.jə.mən/", "The ability to make good judgments and quick decisions in experimental design.", "From Latin acumen ('sharpness').", "Her diagnostic acumen enabled the rapid identification of a novel rare genetic variant.", "Reviewers praised the author's methodological acumen in isolating single-cell RNA transcriptomes.", ["Manuscript Editing"], ["Perspicacity", "Astuteness", "Insight"], ["Incompetence", "Obtuse"]),
  word("Adjudicate", "verb", "/əˈdʒuː.dɪ.keɪt/", "To make a formal judgment or decision about a disputed scientific issue.", "From Latin adjudicatus ('judged').", "A third independent peer reviewer was brought in to adjudicate conflicting opinions.", "The editorial committee met to adjudicate priority disputes between two concurrent submissions.", ["Editorial Meetings", "Peer Review"], ["Arbitrate", "Determine", "Settle"], ["Defer", "Ignore"]),
  word("Admonition", "noun", "/ˌæd.məˈnɪʃ.ən/", "A gentle or authoritative warning or critique regarding experimental rigor.", "From Latin admonitio ('warning').", "The reviewer's admonition regarding small sample sizes prompted an additional power calculation.", "Authors heeded the associate editor's admonition to clarify all antibody dilution factors.", ["Peer Review", "Editorial Meetings"], ["Caution", "Warning", "Exhortation"], ["Praise", "Approval"]),
  word("Adumbrate", "verb", "/ˈæd.əm.breɪt/", "To represent or outline in a sketchy, preliminary, or faint way.", "From Latin adumbratus ('shadowed').", "The preliminary communication adumbrates a novel mechanism for chromatin remodeling.", "In the discussion section, the authors adumbrated future directions for clinical translation.", ["Manuscript Editing"], ["Foreshadow", "Outline", "Intimate"], ["Elaborate", "Explicate"]),
  word("Aegis", "noun", "/ˈiː.dʒɪs/", "The protection, backing, or sponsorship of a person or scientific institution.", "From Ancient Greek αἰγίς (aigís, 'shield').", "The multi-center phase III clinical trial was conducted under the aegis of the National Institutes of Health.", "Under the aegis of the editorial society, standardized reporting guidelines were promulgated.", ["Editorial Meetings"], ["Auspices", "Patronage", "Sponsorship"], ["Opposition"]),
  word("Affinity", "noun", "/əˈfɪn.ə.ti/", "A natural liking or strong binding attraction between molecules or receptor sites.", "From Latin affinitas ('relationship').", "Surface plasmon resonance demonstrated high-affinity antibody binding with a Kd of 0.2 nM.", "The referee asked for binding affinity measurements comparing wild-type and mutant peptides.", ["Life Sciences", "Peer Review"], ["Avidity", "Attraction", "Propensity"], ["Aversion", "Repulsion"]),
  word("Aggregation", "noun", "/ˌæɡ.rɪˈɡeɪ.ʃən/", "The formation of a number of biological things into a cluster or mass.", "From Latin aggregatio.", "Protein aggregation was monitored using dynamic light scattering across varying pH conditions.", "The reviewer noted that insoluble protein aggregation could confound fluorescence signals.", ["Life Sciences"], ["Clustering", "Accumulation", "Conglomeration"], ["Dispersion", "Dissolution"]),
  word("Alacrity", "noun", "/əˈlæk.rə.ti/", "Brisk and cheerful readiness in responding to referee comments.", "From Latin alacritas ('liveliness').", "The corresponding author addressed all reviewer revisions with impressive thoroughness and alacrity.", "The editorial team processed the breaking pandemic manuscript with unprecedented alacrity.", ["Editorial Meetings", "Peer Review"], ["Promptness", "Eagerness", "Dispatch"], ["Apathy", "Reluctance"]),
  word("Allay", "verb", "/əˈleɪ/", "To diminish or put at rest scientific doubts, fears, or concerns.", "From Old English ālegan ('to lay down').", "Supplementary cell viability controls helped allay reviewer concerns regarding cytotoxicity.", "The authors provided secondary cohort data to allay doubts about generalizability.", ["Peer Review"], ["Assuage", "Mitigate", "Alleviate"], ["Exacerbate", "Heighten"]),
  word("Ameliorate", "verb", "/əˈmiː.li.ə.reɪt/", "To make something bad or unsatisfactory better or more tolerable.", "From Latin melior ('better').", "Administration of the therapeutic antibody ameliorated neuroinflammatory pathology in vivo.", "Reviewers noted that adjusting background noise levels significantly ameliorated plot clarity.", ["Life Sciences", "Manuscript Editing"], ["Improve", "Enhance", "Alleviate"], ["Worsen", "Aggravate"]),
  word("Amplification", "noun", "/ˌæm.plɪ.fɪˈkeɪ.ʃən/", "The process of increasing the volume, magnitude, or copy number of a gene or signal.", "From Latin amplificatio.", "Quantitative PCR revealed a sixfold amplification of the ERBB2 gene in resistant tumor tissue.", "The reviewer requested genomic controls to rule out non-specific PCR amplification artifacts.", ["Life Sciences", "Peer Review"], ["Enlargement", "Expansion", "Potentiation"], ["Attenuation", "Reduction"]),
  word("Anachronistic", "adj.", "/ənˌæk.rəˈnɪs.tɪk/", "Out of date or belonging to a period other than that in which it exists.", "From Greek anakhronismos.", "Using outdated gel electrophoresis alone without mass spectrometry felt anachronistic to peer reviewers.", "The panel highlighted that referencing 20-year-old criteria without modern nomenclature was anachronistic.", ["Peer Review", "Manuscript Editing"], ["Outdated", "Obsolete", "Archaic"], ["Contemporary", "Modern"]),
  word("Analogous", "adj.", "/əˈnæl.ə.ɡəs/", "Comparable in certain respects, typically in a way which makes clearer the nature of the things compared.", "From Greek analogos ('proportionate').", "The murine phenotype was functionally analogous to human early-onset cardiomyopathy.", "The referee agreed that the organoid response was analogous to patient tumor biopsies.", ["Life Sciences", "Peer Review"], ["Comparable", "Equivalent", "Parallel"], ["Disparate", "Unrelated"]),
  word("Anomaly", "noun", "/əˈnɒm.ə.li/", "A deviation from expected theoretical rules, standard physiological baselines, or general control outcomes.", "From Ancient Greek ἀνωμαλία.", "The outlier point in batch 3 was flagged as a technical anomaly caused by a pipette calibration error.", "The reviewer asked whether the transient temperature spike represented a biological anomaly or equipment drift.", ["Life Sciences", "Peer Review"], ["Aberration", "Irregularity", "Outlier"], ["Norm", "Standard"]),
  word("Antecedent", "noun", "/ˌæn.təˈsiː.dənt/", "A thing or event that existed before or logically precedes another.", "From Latin antecedens ('going before').", "Inflammatory cascade activation was identified as the key antecedent to vascular dysfunction.", "The editor requested a clearer explanation of historical antecedents to this research hypothesis.", ["Life Sciences", "Manuscript Editing"], ["Precursor", "Predecessor", "Forerunner"], ["Consequent", "Descendant"]),
  word("Anthropogenic", "adj.", "/ˌæn.θrə.pəˈdʒen.ɪk/", "Originating in human activity, particularly regarding environmental or ecological impact.", "From Greek anthropos ('human') + genesis.", "Anthropogenic chemical discharge caused measurable shifts in estuarine microbial biodiversity.", "The study provides compelling longitudinal evidence of anthropogenic nitrogen deposition.", ["Life Sciences"], ["Human-induced", "Man-made", "Synthetic"], ["Natural", "Biogenic"]),
  word("Antipathy", "noun", "/ænˈtɪp.ə.θi/", "A deep-seated feeling of aversion or opposition toward a hypothesis or method.", "From Greek antipatheia.", "The author expressed strong antipathy toward reductive biomedical paradigms in the introduction.", "Philosophical antipathy between the two academic schools delayed consensus on diagnostic criteria.", ["Editorial Meetings"], ["Aversion", "Hostility", "Antagonism"], ["Affinity", "Sympathy"]),
  word("Antithesis", "noun", "/ænˈtɪθ.ə.sɪs/", "A person or thing that is the direct opposite of someone or something else.", "From Greek antithesis ('opposition').", "The observed rapid regression of the tumor was the exact antithesis of the expected progression.", "This mechanistic conclusion stands as the direct antithesis of the classical dogma.", ["Peer Review", "Manuscript Editing"], ["Polar opposite", "Inverse", "Counterpart"], ["Identity", "Equivalence"]),
  word("Apposite", "adj.", "/ˈæp.ə.zɪt/", "Apt, appropriate, or highly relevant in the circumstances of a manuscript argument.", "From Latin appositus ('applied').", "The author selected an apposite anatomical model to illustrate regional tissue vascularization.", "Reviewers commended the introduction for providing an apposite historical overview of the field.", ["Manuscript Editing"], ["Germane", "Pertinent", "Fitting"], ["Inapposite", "Irrelevant"]),
  word("Approbration", "noun", "/ˌæp.rəˈbeɪ.ʃən/", "Approval or praise, particularly from peer review panels or editorial boards.", "From Latin approbatio.", "The novel CRISPR discovery met with enthusiastic approbation from international reviewers.", "Securing the editor's approbation required providing rigorous orthogonal validation datasets.", ["Peer Review", "Editorial Meetings"], ["Commendation", "Sanction", "Endorsement"], ["Disapproval", "Censure"]),
  word("Assay", "noun", "/ˈæs.eɪ/", "An investigative procedure in laboratory medicine or biological research for measuring a substance.", "From Old French essai ('trial').", "A luminescent ATP cell viability assay was deployed to assess drug toxicity across 12 cell lines.", "The committee inquired whether an orthogonal enzymatic assay was performed to confirm binding.", ["Life Sciences", "Manuscript Editing"], ["Analysis", "Evaluation", "Test"], ["Conjecture", "Guess"]),
  word("Attenuate", "verb", "/əˈten.ju.eɪt/", "To reduce the force, intensity, virulence, or amplitude of a biological signal.", "From Latin attenuatus.", "Pre-treatment with the antioxidant compound significantly attenuated ROS-induced apoptotic signaling.", "Reviewers asked whether siRNA knockdowns attenuated target protein levels by at least 80%.", ["Life Sciences", "Peer Review"], ["Diminish", "Dampen", "Mitigate"], ["Exacerbate", "Amplify"])
];

console.log("Writing vocab file a.json with " + vocab.a.length + " entries...");
fs.writeFileSync(path.join(__dirname, '../src/data/a.json'), JSON.stringify(vocab.a, null, 2));

