import { LexiconWord } from './types';

export const wordsC: LexiconWord[] = [
  { id: 301, word: "Canonical", definition: "According to recognized rules or scientific laws; the standard version.", enExample: "Provide a canonical URL to avoid duplicate content issues.", taExample: "நகல் உள்ளடக்க சிக்கல்களைத் தவிர்க்க ஒரு நிலையான (கனானிக்கல்) URL ஐ வழங்கவும்.", taWord: "நிலையான / அங்கீகரிக்கப்பட்ட", pos: "adj.", synonyms: ["Standard", "Authoritative"], antonyms: ["Unorthodox", "Nonstandard"] },
  { id: 302, word: "Concurrently", definition: "At the same time; simultaneously.", enExample: "The tasks will run concurrently to save time.", taExample: "நேரத்தைச் சேமிக்க பணிகள் ஒரே நேரத்தில் இயங்கும்.", taWord: "ஒரே நேரத்தில்", pos: "adv.", synonyms: ["Simultaneously", "Together"], antonyms: ["Sequentially", "Serially"] },
  { id: 303, word: "Configure", definition: "Shape or put together in a particular form or configuration.", enExample: "Configure the server to accept HTTPS connections.", taExample: "HTTPS இணைப்புகளை ஏற்க சேவையகத்தை உள்ளமைக்கவும்.", taWord: "உள்ளமைத்தல்", pos: "verb", synonyms: ["Set up", "Arrange"], antonyms: ["Dismantle"] },
  { id: 304, word: "Constraint", definition: "A limitation or restriction.", enExample: "Memory is a major constraint on this device.", taExample: "இந்தச் சாதனத்தில் நினைவகம் ஒரு முக்கியக் கட்டுப்பாடாகும்.", taWord: "கட்டுப்பாடு", pos: "noun", synonyms: ["Limitation", "Restriction"], antonyms: ["Freedom", "Liberty"] },
  { id: 305, word: "Convoluted", definition: "Extremely complex and difficult to follow.", enExample: "This legacy code is too convoluted.", taExample: "இந்த பழைய குறியீடு மிகவும் சிக்கலானதாக உள்ளது.", taWord: "சிக்கலான", pos: "adj.", synonyms: ["Complicated", "Complex"], antonyms: ["Simple", "Straightforward"] },
  { id: 306, word: "Correlate", definition: "Have a mutual relationship or connection.", enExample: "Can we correlate the errors with the recent deployment?", taExample: "சமீபத்திய வரிசைப்படுத்தலுடன் பிழைகளைத் தொடர்புபடுத்த முடியுமா?", taWord: "தொடர்புபடுத்துதல்", pos: "verb", synonyms: ["Associate", "Connect"], antonyms: ["Disconnect", "Separate"] },
  { id: 307, word: "Cohesive", definition: "Characterized by or causing cohesion; forming a united whole.", enExample: "The modules form a highly cohesive system.", taExample: "தொகுதிகள் மிகவும் ஒத்திசைவான அமைப்பை உருவாக்குகின்றன.", taWord: "ஒத்திசைவான", pos: "adj.", synonyms: ["United", "Integrated"], antonyms: ["Disjointed", "Fragmented"] },
  { id: 308, word: "Cache", definition: "A collection of items of the same type stored in a hidden or inaccessible place.", enExample: "Clear the cache to see the latest changes.", taExample: "சமீபத்திய மாற்றங்களைக் காண தற்காலிக சேமிப்பை அழிக்கவும்.", taWord: "தற்காலிக சேமிப்பு", pos: "noun", synonyms: ["Store", "Buffer"], antonyms: [] },
  { id: 309, word: "Cascade", definition: "A process whereby something, typically information or knowledge, is successively passed on.", enExample: "The database deletion will cascade to related records.", taExample: "தரவுத்தள நீக்கம் தொடர்புடைய பதிவுகளுக்கும் தொடர்ச்சியாகச் செல்லும்.", taWord: "தொடர்ச்சியாகச் செல்லுதல்", pos: "verb", synonyms: ["Flow", "Pour"], antonyms: ["Halt"] },
  { id: 310, word: "Clunky", definition: "Awkwardly solid, heavy, and outdated.", enExample: "The old user interface feels very clunky.", taExample: "பழைய பயனர் இடைமுகம் மிகவும் விகாரமாக (பழமையானதாக) உணர்கிறது.", taWord: "விகாரமான", pos: "adj.", synonyms: ["Awkward", "Cumbersome"], antonyms: ["Elegant", "Streamlined"] },
  { id: 311, word: "Compile", definition: "Produce (something, especially a list, report, or book) by assembling information collected from other sources.", enExample: "Compile the source code before running tests.", taExample: "சோதனைகளை இயக்குவதற்கு முன் மூலக் குறியீட்டைத் தொகுக்கவும்.", taWord: "தொகுத்தல்", pos: "verb", synonyms: ["Assemble", "Gather"], antonyms: ["Disperse"] },
  { id: 312, word: "Compliant", definition: "Meeting or in accordance with rules or standards.", enExample: "Ensure the app is GDPR compliant.", taExample: "பயன்பாடு GDPR விதிகளுக்கு இணங்குவதை உறுதி செய்யவும்.", taWord: "இணக்கமான", pos: "adj.", synonyms: ["Conforming", "Obedient"], antonyms: ["Noncompliant", "Defiant"] },
  { id: 313, word: "Concatenate", definition: "Link (things) together in a chain or series.", enExample: "Concatenate the first and last name strings.", taExample: "முதல் மற்றும் கடைசிப் பெயர் சரங்களை ஒன்றிணைக்கவும்.", taWord: "ஒன்றிணைத்தல்", pos: "verb", synonyms: ["Join", "Link"], antonyms: ["Separate", "Split"] },
  { id: 314, word: "Consolidate", definition: "Make (something) physically stronger or more solid.", enExample: "We should consolidate our microservices into fewer repos.", taExample: "நமது மைக்ரோ சர்வீஸ்களைக் குறைவான களஞ்சியங்களில் ஒருங்கிணைக்க வேண்டும்.", taWord: "ஒருங்கிணைத்தல்", pos: "verb", synonyms: ["Combine", "Merge"], antonyms: ["Separate", "Divide"] },
  { id: 315, word: "Cryptic", definition: "Having a meaning that is mysterious or obscure.", enExample: "The error message is too cryptic for users.", taExample: "பிழை செய்தி பயனர்களுக்கு மிகவும் புரியாதவாறு உள்ளது.", taWord: "புரியாத", pos: "adj.", synonyms: ["Mysterious", "Obscure"], antonyms: ["Clear", "Obvious"] },
  { id: 316, word: "Cluster", definition: "A group of similar things or people positioned or occurring closely together.", enExample: "We deployed the app to a Kubernetes cluster.", taExample: "நாங்கள் பயன்பாட்டை குபெர்னெட்டீஸ் கிளஸ்டரில் (கொத்தாக) வரிசைப்படுத்தினோம்.", taWord: "கொத்து", pos: "noun", synonyms: ["Group", "Batch"], antonyms: [] },
  { id: 317, word: "Cognitive", definition: "Relating to cognition; mental processes.", enExample: "Reduce the cognitive load on the user interface.", taExample: "பயனர் இடைமுகத்தில் அறிவாற்றல் சுமையைக் குறைக்கவும்.", taWord: "அறிவாற்றல்", pos: "adj.", synonyms: ["Mental", "Intellectual"], antonyms: ["Physical"] },
  { id: 318, word: "Compatible", definition: "Able to exist or occur together without conflict.", enExample: "The new version is fully backward compatible.", taExample: "புதிய பதிப்பு பழைய பதிப்புகளுடன் முழுமையாக இணக்கமானது.", taWord: "இணக்கமான", pos: "adj.", synonyms: ["Suited", "Matching"], antonyms: ["Incompatible", "Conflicting"] },
  { id: 319, word: "Component", definition: "A part or element of a larger whole.", enExample: "Extract this logic into a reusable React component.", taExample: "இந்தத் தர்க்கத்தை மீண்டும் பயன்படுத்தக்கூடிய ரியாக்ட் கூறாகப் பிரிக்கவும்.", taWord: "கூறு", pos: "noun", synonyms: ["Part", "Element"], antonyms: ["Whole", "Entirety"] },
  { id: 320, word: "Contingency", definition: "A future event or circumstance which is possible but cannot be predicted with certainty.", enExample: "What is our contingency plan for server failure?", taExample: "சேவையக செயலிழப்புக்கான நமது மாற்றுத் திட்டம் என்ன?", taWord: "மாற்றுத் திட்டம் / எதிர்பாராத நிகழ்வு", pos: "noun", synonyms: ["Emergency", "Possibility"], antonyms: ["Certainty"] },
  { id: 321, word: "Critical", definition: "Expressing adverse or disapproving comments or judgments; vital.", enExample: "This is a critical bug that needs immediate fixing.", taExample: "இது உடனடியாகத் தீர்க்கப்பட வேண்டிய முக்கியமான பிழையாகும்.", taWord: "முக்கியமான / நெருக்கடியான", pos: "adj.", synonyms: ["Vital", "Crucial"], antonyms: ["Trivial", "Unimportant"] },
  { id: 322, word: "Cumulative", definition: "Increasing or increased in quantity, degree, or force by successive additions.", enExample: "Check the cumulative impact of these small changes.", taExample: "இந்த சிறிய மாற்றங்களின் ஒட்டுமொத்த தாக்கத்தை சரிபார்க்கவும்.", taWord: "ஒட்டுமொத்த", pos: "adj.", synonyms: ["Aggregated", "Accumulative"], antonyms: ["Decreasing", "Subtracting"] },
  { id: 323, word: "Cycle", definition: "A series of events that are regularly repeated in the same order.", enExample: "We are entering the final testing cycle.", taExample: "நாங்கள் இறுதி சோதனை சுழற்சியில் நுழைகிறோம்.", taWord: "சுழற்சி", pos: "noun", synonyms: ["Loop", "Rotation"], antonyms: [] },
  { id: 324, word: "Custom", definition: "Made or done to order for a particular customer.", enExample: "We need a custom solution for this client.", taExample: "இந்த வாடிக்கையாளருக்கு நமக்கு ஒரு தனிப்பயன் தீர்வு தேவை.", taWord: "தனிப்பயன்", pos: "adj.", synonyms: ["Bespoke", "Tailored"], antonyms: ["Standard", "Generic"] },
  { id: 325, word: "Core", definition: "The central or most important part of something.", enExample: "Don't modify the core logic without reviewing.", taExample: "மதிப்பாய்வு செய்யாமல் முக்கிய தர்க்கத்தை மாற்ற வேண்டாம்.", taWord: "மையம் / முக்கிய", pos: "noun", synonyms: ["Center", "Heart"], antonyms: ["Periphery", "Surface"] }  ,
  {
    id: 326,
    word: "Capricious",
    definition: "Given to sudden and unaccountable changes of mood or behavior.",
    enExample: "A capricious and often brutal administration.",
    taExample: "கணிக்க முடியாத மற்றும் அடிக்கடி மிருகத்தனமான நிர்வாகம்.",
    taWord: "கணிக்க முடியாத",
    pos: "adj.",
    synonyms: ["Fickle","Inconstant","Variable"],
    antonyms: ["Stable","Consistent"]
  },
  {
    id: 327,
    word: "Castigate",
    definition: "Reprimand (someone) severely.",
    enExample: "He was castigated for not setting a good example.",
    taExample: "ஒரு நல்ல முன்னுதாரணத்தை அமைக்காததற்காக அவர் கடுமையாக கண்டிக்கப்பட்டார்.",
    taWord: "கடுமையாக கண்டி",
    pos: "verb",
    synonyms: ["Reprimand","Rebuke","Admonish"],
    antonyms: ["Praise","Commend"]
  },
  {
    id: 328,
    word: "Conundrum",
    definition: "A confusing and difficult problem or question.",
    enExample: "One of the most difficult conundrums for the experts.",
    taExample: "நிபுணர்களுக்கு இது மிகவும் கடினமான புதிர்களில் ஒன்றாகும்.",
    taWord: "புதிர்",
    pos: "noun",
    synonyms: ["Problem","Difficult question","Puzzle"],
    antonyms: ["Solution"]
  },
  {
    id: 329,
    word: "Clarify",
    definition: "Make a statement or situation clearer and easier to understand.",
    enExample: "Please clarify the requirements for the API endpoint.",
    taExample: "API முனைக்கான தேவைகளை தெளிவுபடுத்தவும்.",
    taWord: "தெளிவுபடுத்துதல்",
    pos: "verb",
    synonyms: ["Explain", "Elucidate"],
    antonyms: ["Confuse", "Obscure"]
  },
  {
    id: 330,
    word: "Collaborate",
    definition: "Work jointly with others on an activity or project.",
    enExample: "Frontend and backend teams collaborate closely on data schemas.",
    taExample: "முன்-இறுதி மற்றும் பின்-இறுதி அணிகள் தரவுத் திட்டங்களில் நெருக்கமாக இணைந்து செயல்படுகின்றன.",
    taWord: "இணைந்து செயல்படுதல்",
    pos: "verb",
    synonyms: ["Cooperate", "Partner"],
    antonyms: ["Compete", "Oppose"]
  },
  {
    id: 331,
    word: "Comprehensive",
    definition: "Including or dealing with all or nearly all elements or aspects.",
    enExample: "The documentation provides a comprehensive overview of the SDK.",
    taExample: "ஆவணங்கள் எஸ்டிகேவின் முழுமையான மேலோட்டத்தை வழங்குகிறது.",
    taWord: "முழுமையான / விரிவான",
    pos: "adj.",
    synonyms: ["Thorough", "Exhaustive"],
    antonyms: ["Partial", "Incomplete"]
  },
  {
    id: 332,
    word: "Consistent",
    definition: "Acting or done in the same way over time; dependable.",
    enExample: "Maintaining a consistent coding style improves readability.",
    taExample: "சீரான குறியீட்டு பாணியை பராமரிப்பது வாசிப்புத்திறனை மேம்படுத்துகிறது.",
    taWord: "சீரான / நிலையான",
    pos: "adj.",
    synonyms: ["Steady", "Reliable"],
    antonyms: ["Inconsistent", "Erratic"]
  },
  {
    id: 333,
    word: "Convey",
    definition: "Make an idea, impression, or feeling known or understandable to someone.",
    enExample: "Use clear visual feedback to convey state changes.",
    taExample: "நிலை மாற்றங்களைத் தெரிவிக்க தெளிவான காட்சிப் பின்னூட்டத்தைப் பயன்படுத்தவும்.",
    taWord: "தெரிவித்தல் / கடத்துதல்",
    pos: "verb",
    synonyms: ["Communicate", "Express"],
    antonyms: ["Conceal", "Withhold"]
  },
  {
    id: 334,
    word: "Courteous",
    definition: "Polite, respectful, or considerate in manner.",
    enExample: "Maintain a courteous tone in code reviews and discussions.",
    taExample: "குறியீட்டு மதிப்பாய்வுகள் மற்றும் விவாதங்களில் மரியாதையான தொனியைப் பேணுங்கள்.",
    taWord: "மரியாதையான",
    pos: "adj.",
    synonyms: ["Polite", "Respectful"],
    antonyms: ["Rude", "Impolite"]
  },
  {
    id: 335,
    word: "Cultivate",
    definition: "Try to acquire or develop a quality, skill, or relationship.",
    enExample: "Cultivate a culture of continuous learning within the team.",
    taExample: "அணியினரிடையே தொடர்ச்சியான கற்றல் கலாச்சாரத்தை வளர்த்தெடுக்கவும்.",
    taWord: "வளர்த்தெடுத்தல்",
    pos: "verb",
    synonyms: ["Foster", "Develop"],
    antonyms: ["Neglect", "Destroy"]
  },
  {
    id: 336,
    word: "Capacity",
    definition: "The maximum amount that something can contain, produce, or handle.",
    enExample: "The cache server is operating at maximum capacity.",
    taExample: "கேச் சேவையகம் அதிகபட்ச கொள்ளளவில் இயங்குகிறது.",
    taWord: "கொள்ளளவு / திறன்",
    pos: "noun",
    synonyms: ["Volume", "Capability"],
    antonyms: []
  },
  {
    id: 337,
    word: "Circumstance",
    definition: "A fact or condition connected with or relevant to an event or action.",
    enExample: "Under no circumstance should secret keys be committed to source control.",
    taExample: "எந்த சூழ்நிலையிலும் இரகசிய விசைகளை மூலக் கட்டுப்பாட்டில் சேர்க்கக் கூடாது.",
    taWord: "சூழ்நிலை / நிலைமை",
    pos: "noun",
    synonyms: ["Situation", "Condition"],
    antonyms: []
  },
  {
    id: 338,
    word: "Compelling",
    definition: "Evoking interest, attention, or admiration in a powerfully convincing way.",
    enExample: "She presented a compelling business case for the architecture upgrade.",
    taExample: "கட்டமைப்பு மேம்பாட்டிற்காக அவள் ஒரு ஈர்க்கக்கூடிய வணிக காரணத்தை முன்வைத்தார்.",
    taWord: "ஈர்க்கக்கூடிய / கட்டாயப்படுத்தும்",
    pos: "adj.",
    synonyms: ["Convincing", "Persuasive"],
    antonyms: ["Unconvincing", "Boring"]
  }
];
