import { LexiconWord } from './types';

export const wordsF: LexiconWord[] = [
  { id: 601, word: "Facade", definition: "An outward appearance that is maintained to conceal a less pleasant or creditable reality; a design pattern.", enExample: "The library provides a simple facade over the complex API.", taExample: "இந்த நூலகம் சிக்கலான API-யின் மீது ஒரு எளிய முகப்பை வழங்குகிறது.", taWord: "முகப்பு", pos: "noun", synonyms: ["Front", "Veneer"], antonyms: ["Core", "Interior"] },
  { id: 602, word: "Facilitate", definition: "Make (an action or process) easy or easier.", enExample: "The new tool will facilitate faster code reviews.", taExample: "புதிய கருவி விரைவான குறியீடு மதிப்பாய்வுகளை எளிதாக்கும்.", taWord: "எளிதாக்குதல்", pos: "verb", synonyms: ["Ease", "Assist"], antonyms: ["Hinder", "Impede"] },
  { id: 603, word: "Fallback", definition: "An alternative plan that may be used in an emergency.", enExample: "Provide a fallback image in case the primary one fails to load.", taExample: "முதன்மையானது ஏற்றத் தவறினால் காப்புப் படமாக ஒன்றை வழங்கவும்.", taWord: "காப்பு / மாற்று", pos: "noun", synonyms: ["Alternative", "Backup"], antonyms: ["Primary"] },
  { id: 604, word: "Feasible", definition: "Possible to do easily or conveniently.", enExample: "Is it feasible to implement this feature by Friday?", taExample: "வெள்ளிக்கிழமைக்குள் இந்த அம்சத்தைச் செயல்படுத்துவது சாத்தியமா?", taWord: "சாத்தியமான", pos: "adj.", synonyms: ["Possible", "Practical"], antonyms: ["Impossible", "Impractical"] },
  { id: 605, word: "Feature", definition: "A distinctive attribute or aspect of something.", enExample: "The team is working on a highly requested feature.", taExample: "அதிகம் கோரப்பட்ட ஒரு அம்சத்தில் குழு வேலை செய்து வருகிறது.", taWord: "அம்சம்", pos: "noun", synonyms: ["Attribute", "Characteristic"], antonyms: ["Bug", "Flaw"] },
  { id: 606, word: "Federation", definition: "A group of computing or network providers agreeing upon standards of operation.", enExample: "We use a GraphQL federation approach to combine multiple schemas.", taExample: "பல திட்டங்களை இணைக்க கிராஃப்கியூஎல் கூட்டமைப்பு அணுகுமுறையைப் பயன்படுத்துகிறோம்.", taWord: "கூட்டமைப்பு", pos: "noun", synonyms: ["Union", "Alliance"], antonyms: ["Separation"] },
  { id: 607, word: "Fetch", definition: "Go for and then bring back (someone or something).", enExample: "Fetch the user profile data from the server.", taExample: "சேவையகத்திலிருந்து பயனர் சுயவிவரத் தரவைப் பெற்று வரவும்.", taWord: "பெற்று வருதல்", pos: "verb", synonyms: ["Retrieve", "Get"], antonyms: ["Send", "Push"] },
  { id: 608, word: "Filter", definition: "Process or assess items in order to reject those that are unwanted.", enExample: "Filter the array to remove empty values.", taExample: "வெற்று மதிப்புகளை அகற்ற வரிசையை வடிகட்டவும்.", taWord: "வடிகட்டுதல்", pos: "verb", synonyms: ["Sift", "Screen"], antonyms: ["Combine", "Include"] },
  { id: 609, word: "Flaky", definition: "Unreliable or unpredictable; prone to breaking intermittently.", enExample: "We need to fix the flaky tests in the CI pipeline.", taExample: "சிஐ பைப்லைனில் உள்ள நம்பகமற்ற (அடிக்கடி தோல்வியடையும்) சோதனைகளை நாம் சரிசெய்ய வேண்டும்.", taWord: "நம்பகமற்ற", pos: "adj.", synonyms: ["Unreliable", "Inconsistent"], antonyms: ["Stable", "Reliable"] },
  { id: 610, word: "Fleet", definition: "A group of vehicles or instances operating together.", enExample: "We deployed the update to our entire fleet of servers.", taExample: "எங்கள் சேவையகங்களின் முழுத் தொகுதிக்கும் (கப்பற்படைக்கும்) புதுப்பிப்பை வரிசைப்படுத்தினோம்.", taWord: "தொகுதி / கப்பற்படை", pos: "noun", synonyms: ["Group", "Collection"], antonyms: ["Single"] },
  { id: 611, word: "Flush", definition: "Cleanse (something) by passing large quantities of liquid through it; clear a buffer.", enExample: "Flush the Redis cache to ensure fresh data.", taExample: "புதிய தரவை உறுதி செய்ய ரெடிஸ் தற்காலிக சேமிப்பை அழிக்கவும் (ஃப்ளஷ் செய்யவும்).", taWord: "அழித்தல் (பப்பரை)", pos: "verb", synonyms: ["Clear", "Purge"], antonyms: ["Store", "Retain"] },
  { id: 612, word: "Footprint", definition: "The area or amount of space occupied by something; resources used.", enExample: "The new app version has a significantly smaller memory footprint.", taExample: "புதிய பயன்பாட்டுப் பதிப்பு கணிசமாக குறைந்த நினைவக இடத்தையே (தடம்) பயன்படுத்துகிறது.", taWord: "தடம் / அளவு", pos: "noun", synonyms: ["Impact", "Size"], antonyms: [] },
  { id: 613, word: "Foreground", definition: "The part of a view that is nearest to the observer; currently active application.", enExample: "The app must remain responsive while running in the foreground.", taExample: "முன்புறத்தில் இயங்கும் போது பயன்பாடு பதிலளிக்கக்கூடியதாக இருக்க வேண்டும்.", taWord: "முன்புறம்", pos: "noun", synonyms: ["Front", "Active"], antonyms: ["Background"] },
  { id: 614, word: "Fork", definition: "Divide into two parts; create a copy of a repository.", enExample: "Fork the open-source repository to make your own changes.", taExample: "உங்கள் சொந்த மாற்றங்களைச் செய்ய திறந்த-மூல களஞ்சியத்தை நகலெடுக்கவும் (ஃபோர்க் செய்யவும்).", taWord: "நகலெடுத்தல் (களஞ்சியத்தை) / பிரித்தல்", pos: "verb", synonyms: ["Split", "Branch"], antonyms: ["Merge", "Join"] },
  { id: 615, word: "Format", definition: "The way in which something is arranged or set out.", enExample: "Ensure the date format is consistent across the application.", taExample: "பயன்பாடு முழுவதும் தேதி வடிவமைப்பு சீராக இருப்பதை உறுதி செய்யவும்.", taWord: "வடிவமைப்பு", pos: "noun", synonyms: ["Layout", "Arrangement"], antonyms: [] },
  { id: 616, word: "Fragment", definition: "A small part broken or separated off something.", enExample: "The data was sent in several fragments over the network.", taExample: "நெட்வொர்க் வழியாக தரவு பல துண்டுகளாக அனுப்பப்பட்டது.", taWord: "துண்டு / பகுதி", pos: "noun", synonyms: ["Piece", "Segment"], antonyms: ["Whole", "Complete"] },
  { id: 617, word: "Framework", definition: "An essential supporting structure; a platform for developing software.", enExample: "React is a popular framework for building user interfaces.", taExample: "பயனர் இடைமுகங்களை உருவாக்குவதற்கு ரியாக்ட் ஒரு பிரபலமான கட்டமைப்பாகும்.", taWord: "கட்டமைப்பு", pos: "noun", synonyms: ["Structure", "Platform"], antonyms: [] },
  { id: 618, word: "Friction", definition: "The resistance that one surface or object encounters when moving over another; conflict.", enExample: "We want to reduce the friction in the user onboarding process.", taExample: "பயனர் உள்ளிணைப்புச் செயல்பாட்டில் உள்ள தடைகளை (உராய்வுகளை) குறைக்க விரும்புகிறோம்.", taWord: "தடை / உராய்வு", pos: "noun", synonyms: ["Resistance", "Conflict"], antonyms: ["Ease", "Harmony"] },
  { id: 619, word: "Fulcrum", definition: "The point on which a lever rests or is supported; something that plays a central role.", enExample: "The database is the fulcrum of our entire architecture.", taExample: "தரவுத்தளமே எங்கள் முழு கட்டமைப்பின் மையப்புள்ளியாகும்.", taWord: "மையப்புள்ளி", pos: "noun", synonyms: ["Pivot", "Center"], antonyms: ["Edge"] },
  { id: 620, word: "Fundamental", definition: "Forming a necessary base or core; of central importance.", enExample: "Understanding algorithms is fundamental for a computer scientist.", taExample: "கணினி அறிவியலாளருக்கு வழிமுறைகளைப் புரிந்துகொள்வது அடிப்படையானது.", taWord: "அடிப்படையான", pos: "adj.", synonyms: ["Basic", "Core"], antonyms: ["Advanced", "Peripheral"] },
  { id: 621, word: "Fungible", definition: "Able to replace or be replaced by another identical item.", enExample: "Compute resources in the cloud are highly fungible.", taExample: "கிளவுடில் உள்ள கணினி வளங்கள் ஒன்றால் மற்றொன்றை எளிதாக மாற்றக்கூடியவை.", taWord: "மாற்றக்கூடிய", pos: "adj.", synonyms: ["Interchangeable", "Replaceable"], antonyms: ["Unique", "Incomparable"] },
  { id: 622, word: "Fuse", definition: "Join or blend to form a single entity.", enExample: "We will fuse the two data streams into a single dashboard.", taExample: "இரண்டு தரவு நீரோடைகளையும் ஒரு ஒற்றை டாஷ்போர்டாக இணைப்போம்.", taWord: "இணைத்தல்", pos: "verb", synonyms: ["Combine", "Merge"], antonyms: ["Separate", "Divide"] },
  { id: 623, word: "Futile", definition: "Incapable of producing any useful result; pointless.", enExample: "It is futile to optimize code before measuring its performance.", taExample: "குறியீட்டின் செயல்திறனை அளவிடுவதற்கு முன்பு அதனை மேம்படுத்துவது பயனற்றது.", taWord: "பயனற்ற", pos: "adj.", synonyms: ["Useless", "Pointless"], antonyms: ["Useful", "Effective"] },
  { id: 624, word: "Fuzzy", definition: "Difficult to perceive clearly or understand; a type of approximate matching.", enExample: "Implement a fuzzy search to tolerate minor spelling mistakes.", taExample: "சிறிய எழுத்துப்பிழைகளைப் பொறுத்துக்கொள்ள ஃபஸி (தோராயமான) தேடலை செயல்படுத்தவும்.", taWord: "தெளிவற்ற / தோராயமான", pos: "adj.", synonyms: ["Approximate", "Blurry"], antonyms: ["Exact", "Precise"] },
  { id: 625, word: "Formulate", definition: "Create or devise methodically.", enExample: "Formulate a plan for the next sprint.", taExample: "அடுத்த ஸ்பிரிண்டிற்கான திட்டத்தை வகுக்கவும்.", taWord: "வகுத்தல்", pos: "verb", synonyms: ["Devise", "Develop"], antonyms: ["Destroy", "Ruined"] }  ,
  {
    id: 626,
    word: "Facetious",
    definition: "Treating serious issues with deliberately inappropriate humor.",
    enExample: "A facetious remark.",
    taExample: "ஒரு வேடிக்கையான கருத்து.",
    taWord: "வேடிக்கையான",
    pos: "adj.",
    synonyms: ["Flippant","Glib","Tongue-in-cheek"],
    antonyms: ["Serious","Solemn"]
  },
  {
    id: 627,
    word: "Fallacious",
    definition: "Based on a mistaken belief.",
    enExample: "Fallacious arguments.",
    taExample: "தவறான வாதங்கள்.",
    taWord: "தவறான",
    pos: "adj.",
    synonyms: ["False","Untrue","Wrong"],
    antonyms: ["True","Correct"]
  },
  {
    id: 628,
    word: "Fastidious",
    definition: "Very attentive to and concerned about accuracy and detail.",
    enExample: "He chooses his words with fastidious care.",
    taExample: "அவர் தனது வார்த்தைகளை மிகவும் நேர்த்தியான கவனத்துடன் தேர்ந்தெடுக்கிறார்.",
    taWord: "நேர்த்தியான",
    pos: "adj.",
    synonyms: ["Scrupulous","Punctilious","Meticulous"],
    antonyms: ["Careless","Sloppy"]
  },
  {
    id: 629,
    word: "Factor",
    definition: "A fact or condition that contributes to a particular result or decision.",
    enExample: "Latency is a critical factor when choosing a cloud region.",
    taExample: "கிளவுட் பிராந்தியத்தைத் தேர்ந்தெடுக்கும்போது தாமதம் ஒரு முக்கிய காரணியாகும்.",
    taWord: "காரணி",
    pos: "noun",
    synonyms: ["Element", "Component"],
    antonyms: []
  },
  {
    id: 630,
    word: "Flexible",
    definition: "Capable of modifying to respond to altered circumstances or conditions.",
    enExample: "The design system provides flexible components for different screen sizes.",
    taExample: "வடிவமைப்பு அமைப்பு வெவ்வேறு திரை அளவுகளுக்கு நெகிழ்வான கூறுகளை வழங்குகிறது.",
    taWord: "நெகிழ்வான",
    pos: "adj.",
    synonyms: ["Adaptable", "Versatile"],
    antonyms: ["Rigid", "Inflexible"]
  },
  {
    id: 631,
    word: "Focus",
    definition: "The main center of interest, attention, or activity.",
    enExample: "Our immediate focus is resolving the memory leak before release.",
    taExample: "வெளியீட்டிற்கு முன் நினைவக கசிவை தீர்ப்பதே நமது உடனடி கவனமாகும்.",
    taWord: "கவனம் / மையம்",
    pos: "noun",
    synonyms: ["Emphasis", "Priority"],
    antonyms: ["Distraction"]
  },
  {
    id: 632,
    word: "Formal",
    definition: "Done in accordance with established rules, procedures, or conventions.",
    enExample: "We conducted a formal security audit prior to launching.",
    taExample: "அறிமுகப்படுத்துவதற்கு முன் நாங்கள் ஒரு முறையான பாதுகாப்பு தணிக்கையை நடத்தினோம்.",
    taWord: "முறையான",
    pos: "adj.",
    synonyms: ["Official", "Systematic"],
    antonyms: ["Informal", "Casual"]
  },
  {
    id: 633,
    word: "Formidable",
    definition: "Inspiring respect or awe through being impressively capable or powerful.",
    enExample: "She is a formidable architect who modernized our legacy platform.",
    taExample: "அவள் எங்கள் பழைய தளத்தை நவீனமாக்கிய ஒரு வல்லமைமிக்க வடிவமைப்பாளர்.",
    taWord: "வல்லமைமிக்க / அஞ்சத்தக்க",
    pos: "adj.",
    synonyms: ["Impressive", "Powerful"],
    antonyms: ["Weak", "Insignificant"]
  },
  {
    id: 634,
    word: "Foster",
    definition: "Encourage or promote the development or growth of something beneficial.",
    enExample: "Open feedback channels foster trust and continuous improvement.",
    taExample: "திறந்த கருத்து வழிகள் நம்பிக்கையையும் தொடர்ச்சியான மேம்பாட்டையும் வளர்க்கின்றன.",
    taWord: "வளர்த்தெடுத்தல் / ஊக்குவித்தல்",
    pos: "verb",
    synonyms: ["Encourage", "Nurture"],
    antonyms: ["Suppress", "Discourage"]
  },
  {
    id: 635,
    word: "Fulfill",
    definition: "Achieve, satisfy, or carry out a requirement, promise, or goal.",
    enExample: "The updated API fulfills all user accessibility guidelines.",
    taExample: "புதுப்பிக்கப்பட்ட API அனைத்து பயனர் அணுகல் வழிகாட்டுதல்களையும் நிறைவேற்றுகிறது.",
    taWord: "நிறைவேற்றுதல் / பூர்த்தி செய்தல்",
    pos: "verb",
    synonyms: ["Satisfy", "Accomplish"],
    antonyms: ["Fail", "Neglect"]
  },
  {
    id: 636,
    word: "Function",
    definition: "The purpose or natural action of a person, mechanism, or software module.",
    enExample: "The core function of this module is data validation.",
    taExample: "இந்த தொகுதியின் முக்கிய செயல்பாடு தரவு சரிபார்ப்பு ஆகும்.",
    taWord: "செயல்பாடு / பணி",
    pos: "noun",
    synonyms: ["Purpose", "Role"],
    antonyms: []
  },
  {
    id: 637,
    word: "Fundamental",
    definition: "Forming a necessary base or core of central importance.",
    enExample: "Data structure efficiency is fundamental to backend scaling.",
    taExample: "பின்-இறுதி அளவிடுதலுக்கு தரவு கட்டமைப்பு செயல்திறன் அடிப்படையானது.",
    taWord: "அடிப்படையான",
    pos: "adj.",
    synonyms: ["Essential", "Core"],
    antonyms: ["Peripheral", "Secondary"]
  },
  {
    id: 638,
    word: "Feedback",
    definition: "Information about reactions or performance used as a basis for improvement.",
    enExample: "Constructive feedback during pull requests helps junior developers grow.",
    taExample: "புல் கோரிக்கைகளின் போது ஆக்கபூர்வமான பின்னூட்டம் இளநிலை டெவலப்பர்கள் வளர உதவுகிறது.",
    taWord: "பின்னூட்டம்",
    pos: "noun",
    synonyms: ["Reaction", "Response"],
    antonyms: []
  }
];
